security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
            json_login:
                check_path: /authentication/login
                username_path: security.credentials.login
                password_path: security.credentials.password
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800

    access_control:
        ## security::src/Controller/HomeController
        - { path: ^/$, roles: IS_AUTHENTICATED_FULLY }

        ## security::src/Controller/SecurityController
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/authentication/re-login, roles: [IS_AUTHENTICATED_REMEMBERED] }

        ## security::src/Controller/UserController@
        - { path: ^/user/signin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/list, roles: [ROLE_ADMIN] }
