version: '3.7'
services:
  postgres:
    image: postgres
    container_name: fantastic_postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fantastic
      PGDATA: /var/sql
    ports:
      - 5555:5432
    volumes:
      - .docker/sql:/var/sql
  php:
    build:
      context: .docker/php-fpm
      args:
        TIMEZONE: ${TIMEZONE}
    container_name: fantastic_php
    volumes:
      - ../fantastic-clover:/projetos/fantastic-clover:cached
      - .docker/logs/symfony:/projetos/fantastic-clover/var/log:cached
    links:
      - postgres
  nginx:
    build: .docker/nginx
    container_name: fantastic_nginx
    ports:
      - 8081:80
    links:
      - php
    volumes:
      - .docker/logs/nginx:/var/log/nginx:cached
      - ../fantastic-clover:/projetos/fantastic-clover:cached
